#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource", IsApplication=true)]

namespace SoToGo.Plugins.Pushwoosh.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int MvxBind = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int MvxDropDownItemTemplate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int MvxGroupItemTemplate = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int MvxItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int MvxLang = 2130771975;
			
			// aapt resource value: 0x7f01000c
			public const int MvxSource = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int MvxTemplate = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_google_signin_btn_text_dark = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_light = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splash = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MvvmCrossTagId = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MvxBindingTagUnique = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int adjust_height = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int adjust_width = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int auto = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int dark = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int icon_only = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int light = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int myButton = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int none = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int standard = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int wide = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SplashScreen = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060013
			public const int app_name = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_enable_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_ticker = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unknown_issue = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_unsupported_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_wear_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_open_on_phone = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text_long = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int hello = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int library_name = 2131099665;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MvxBinding = new int[]
			{
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771976};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771979};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771980};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
