#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource", IsApplication=true)]

namespace SoToGo.Plugins.Pushwoosh.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxBind;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxLang;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxSource;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.MvxTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.buttonSize = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.buttonSize;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.circleCrop = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.circleCrop;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.colorScheme = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.colorScheme;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.imageAspectRatio = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.imageAspectRatio;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.imageAspectRatioAdjust = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.imageAspectRatioAdjust;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Attribute.scopeUris = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Attribute.scopeUris;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_action_bar_splitter = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_action_bar_splitter;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_dark_default = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_default;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_light_default = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_light_default;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_google_signin_btn_text_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_dark_default = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_light_default = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_default;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Color.common_plus_signin_btn_text_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_full_open_on_phone = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_full_open_on_phone;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_ic_googleplayservices = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_ic_googleplayservices;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.MvvmCrossTagId = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvvmCrossTagId;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.MvxBindingTagUnique = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.MvxBindingTagUnique;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.adjust_height = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.adjust_height;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.adjust_width = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.adjust_width;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.auto = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.auto;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.dark = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.dark;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.icon_only = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.icon_only;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.light = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.light;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.none = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.none;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.standard = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.standard;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Id.wide = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Id.wide;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Integer.google_play_services_version = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Integer.google_play_services_version;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.auth_google_play_services_client_facebook_display_name = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.auth_google_play_services_client_google_display_name = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.auth_google_play_services_client_google_display_name;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_api_unavailable_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_api_unavailable_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_enable_button = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_enable_button;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_enable_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_enable_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_enable_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_enable_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_install_button = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_install_button;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_install_text_phone = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_install_text_phone;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_install_text_tablet = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_install_text_tablet;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_install_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_install_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_invalid_account_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_invalid_account_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_invalid_account_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_invalid_account_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_network_error_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_network_error_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_network_error_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_network_error_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_notification_ticker = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_notification_ticker;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_restricted_profile_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_restricted_profile_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_restricted_profile_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_restricted_profile_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_sign_in_failed_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_sign_in_failed_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_unknown_issue = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_unknown_issue;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_unsupported_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_unsupported_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_unsupported_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_unsupported_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_update_button = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_update_button;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_update_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_update_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_update_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_update_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_updating_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_updating_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_updating_title = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_updating_title;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_google_play_services_wear_update_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_google_play_services_wear_update_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_open_on_phone = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_open_on_phone;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_signin_button_text = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_signin_button_text;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.common_signin_button_text_long = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.common_signin_button_text_long;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.String.library_name = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.String.library_name;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.LoadingImageView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.LoadingImageView;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.LoadingImageView_circleCrop = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.LoadingImageView_circleCrop;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxBinding = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxBinding_MvxBind = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxBinding_MvxLang = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxControl = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxExpandableListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxImageView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxImageView_MvxSource = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxListView = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.SignInButton = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.SignInButton;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.SignInButton_buttonSize = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.SignInButton_buttonSize;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.SignInButton_colorScheme = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.SignInButton_colorScheme;
			global::SoToGo.Plugins.Pushwoosh.Droid.Resource.Styleable.SignInButton_scopeUris = global::SoToGo.Plugins.Pushwoosh.Sample.Droid.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int MvxBind = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int MvxDropDownItemTemplate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int MvxGroupItemTemplate = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int MvxItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int MvxLang = 2130771975;
			
			// aapt resource value: 0x7f01000c
			public const int MvxSource = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int MvxTemplate = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_action_bar_splitter = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_dark_default = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_dark_disabled = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark_focused = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_dark_pressed = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_light = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_light_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_signin_btn_text_light_pressed = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_plus_signin_btn_text_dark = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int common_plus_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_plus_signin_btn_text_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_plus_signin_btn_text_dark_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_plus_signin_btn_text_dark_pressed = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int common_plus_signin_btn_text_light = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int common_plus_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_light_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_light_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_plus_signin_btn_text_light_pressed = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int splash = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MvvmCrossTagId = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MvxBindingTagUnique = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int adjust_height = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int adjust_width = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int auto = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int dark = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int icon_only = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int light = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int none = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int standard = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int wide = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SplashScreen = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060021
			public const int app_name = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int auth_google_play_services_client_facebook_display_name = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int auth_google_play_services_client_google_display_name = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_api_unavailable_text = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_enable_button = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_phone = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_text_tablet = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_title = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_invalid_account_title = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_network_error_title = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_restricted_profile_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_restricted_profile_title = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_sign_in_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_sign_in_failed_title = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_unknown_issue = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unsupported_text = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_unsupported_title = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_button = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_title = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_wear_update_text = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int common_open_on_phone = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int common_signin_button_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int common_signin_button_text_long = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int hello = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int library_name = 2131099679;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MvxBinding = new int[]
			{
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771976};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771979};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771980};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
